/**
 * GET  /api/projects/[projectId]/rfis — list RFIs in a project.
 * POST /api/projects/[projectId]/rfis — create an RFI log entry.
 *
 * Per SPEC_PHASE3_WEB.md §5 + §6 (S19 RFI log).
 *
 * Per BR-DC2: RFI refs are auto-generated as "RFI-###" via the pure domain
 *           function nextRfiRef(existingRefs, deletedRefs). The high-water
 *           mark INCLUDES soft-deleted refs (BR-DC3 / GT-DC3 — never reused).
 *
 * Per BR-DC6: default review period = 7 calendar days. Overdue check happens
 *           in the dashboard route (via isOverdue) — not here.
 * Per BR-DC7: default status = OPEN.
 *
 * Per BR-WEB-5: both routes verify the project exists AND is owned by the
 *           session user.
 * Per BR-WEB-8: POST writes AuditLog.
 * Per BR-WEB-11: POST body validated with zod (RfiInputSchema, minus ref).
 */

import { Prisma } from "@prisma/client";
import {
  withErrorHandler,
  json,
  created,
  notFound,
  conflict,
  writeAuditLog,
} from "@/lib/api-helpers";
import { requireUserId } from "@/lib/auth";
import { getServices } from "@/lib/services";
import { verifyProjectOwnership } from "@/app/api/_lib/boq-helpers";
import { RfiInputSchema } from "@shared/schemas/doccontrol/entities";
import { nextRfiRef } from "@domain/doccontrol/numbering";

interface RouteContext {
  params: Promise<{ projectId: string }>;
}

// ─── GET list ─────────────────────────────────────────────────────────────

export const GET = withErrorHandler(async (_req: Request, ctx: RouteContext) => {
  const userId = await requireUserId();
  const { projectId } = await ctx.params;
  const services = getServices();

  const project = await verifyProjectOwnership(projectId, userId);
  if (!project) return notFound("Project not found");

  const rfis = await services.rfis.list(projectId);
  return json({ rfis });
});

// ─── POST create ──────────────────────────────────────────────────────────

export const POST = withErrorHandler(async (req: Request, ctx: RouteContext) => {
  const userId = await requireUserId();
  const { projectId } = await ctx.params;
  const services = getServices();

  const project = await verifyProjectOwnership(projectId, userId);
  if (!project) return notFound("Project not found");

  const body = await req.json();
  // Strip projectId + ref — the URL + numbering domain are the sources of truth.
  const {
    projectId: _ignoredProject,
    ref: _ignoredRef,
    ...rest
  } = body as Record<string, unknown>;
  // .omit({ ref: true }) — ref is auto-generated by the numbering domain.
  const RfiCreateBodySchema = RfiInputSchema.omit({ ref: true });
  const input = RfiCreateBodySchema.parse({ ...rest, projectId });

  // ─── Architecture proof: call the pure domain numbering function ───
  const liveRfis = await services.rfis.list(projectId, true);
  const existingRefs = liveRfis.filter((r) => r.deletedAt === null).map((r) => r.ref);
  const deletedRefs = liveRfis.filter((r) => r.deletedAt !== null).map((r) => r.ref);
  const ref = nextRfiRef(existingRefs, deletedRefs);

  try {
    const rfi = await services.rfis.create({
      projectId,
      ref,
      questionEn: input.questionEn,
      questionAr: input.questionAr ?? null,
      linkedDrawingId: input.linkedDrawingId ?? null,
      sentDate: input.sentDate ?? null,
      reviewPeriodDays: input.reviewPeriodDays,
      status: input.status,
    });

    await writeAuditLog({
      action: "rfi.create",
      entityType: "Rfi",
      entityId: rfi.id,
      afterJson: rfi,
    });

    return created(rfi);
  } catch (err) {
    if (err instanceof Prisma.PrismaClientKnownRequestError && err.code === "P2002") {
      return conflict(`RFI ref "${ref}" already exists in this project`);
    }
    throw err;
  }
});
