/**
 * GET  /api/projects/[projectId]/correspondence — list correspondence in a project.
 * POST /api/projects/[projectId]/correspondence — create a correspondence entry.
 *
 * Per SPEC_PHASE3_WEB.md §5 + §6 (S20 Correspondence).
 *
 * Per BR-DC2: correspondence refs are auto-generated as "IN-###" or "OUT-###"
 *           via the pure domain function nextCorrespondenceRef(direction,
 *           existingRefs, deletedRefs). INCOMING and OUTGOING have INDEPENDENT
 *           sequences. Soft-deleted refs count toward the high-water mark
 *           (BR-DC3 / GT-DC3 — never reused).
 *
 * Per BR-DC10: a Correspondence row with type=TRANSMITTAL has child
 *           TransmittalLine rows — those are managed via the transmittal-lines
 *           sub-resource route.
 *
 * Per BR-WEB-5: both routes verify the project exists AND is owned by the
 *           session user.
 * Per BR-WEB-8: POST writes AuditLog.
 * Per BR-WEB-11: POST body validated with zod (CorrespondenceInputSchema, minus ref).
 */

import { Prisma } from "@prisma/client";
import {
  withErrorHandler,
  json,
  created,
  notFound,
  conflict,
  writeAuditLog,
} from "@/lib/api-helpers";
import { requireUserId } from "@/lib/auth";
import { getServices } from "@/lib/services";
import { verifyProjectOwnership } from "@/app/api/_lib/boq-helpers";
import { CorrespondenceInputSchema } from "@shared/schemas/doccontrol/entities";
import { nextCorrespondenceRef } from "@domain/doccontrol/numbering";

interface RouteContext {
  params: Promise<{ projectId: string }>;
}

// ─── GET list ─────────────────────────────────────────────────────────────

export const GET = withErrorHandler(async (_req: Request, ctx: RouteContext) => {
  const userId = await requireUserId();
  const { projectId } = await ctx.params;
  const services = getServices();

  const project = await verifyProjectOwnership(projectId, userId);
  if (!project) return notFound("Project not found");

  const correspondences = await services.correspondence.list(projectId);
  return json({ correspondences });
});

// ─── POST create ──────────────────────────────────────────────────────────

export const POST = withErrorHandler(async (req: Request, ctx: RouteContext) => {
  const userId = await requireUserId();
  const { projectId } = await ctx.params;
  const services = getServices();

  const project = await verifyProjectOwnership(projectId, userId);
  if (!project) return notFound("Project not found");

  const body = await req.json();
  // Strip projectId + ref — URL + numbering domain are the sources of truth.
  const {
    projectId: _ignoredProject,
    ref: _ignoredRef,
    ...rest
  } = body as Record<string, unknown>;
  // .omit({ ref: true }) — ref is auto-generated by the numbering domain.
  const CorrespondenceCreateBodySchema = CorrespondenceInputSchema.omit({ ref: true });
  const input = CorrespondenceCreateBodySchema.parse({ ...rest, projectId });

  // ─── Architecture proof: call the pure domain numbering function ───
  // Filter the live + deleted lists by direction so IN/OUT sequences are
  // independent (BR-DC2). The nextCorrespondenceRef function only counts
  // refs that match the requested direction's prefix.
  const allCorrespondence = await services.correspondence.list(projectId, true);
  const sameDirection = allCorrespondence.filter(
    (c) => c.direction === input.direction,
  );
  const existingRefs = sameDirection
    .filter((c) => c.deletedAt === null)
    .map((c) => c.ref);
  const deletedRefs = sameDirection
    .filter((c) => c.deletedAt !== null)
    .map((c) => c.ref);
  const ref = nextCorrespondenceRef(input.direction, existingRefs, deletedRefs);

  try {
    const correspondence = await services.correspondence.create({
      projectId,
      ref,
      direction: input.direction,
      type: input.type,
      date: input.date,
      subjectEn: input.subjectEn,
      subjectAr: input.subjectAr ?? null,
      fromParty: input.fromParty,
      toParty: input.toParty,
      bodyEn: input.bodyEn ?? null,
      bodyAr: input.bodyAr ?? null,
    });

    await writeAuditLog({
      action: "correspondence.create",
      entityType: "Correspondence",
      entityId: correspondence.id,
      afterJson: correspondence,
    });

    return created(correspondence);
  } catch (err) {
    if (err instanceof Prisma.PrismaClientKnownRequestError && err.code === "P2002") {
      return conflict(
        `Correspondence ref "${ref}" already exists in this project`,
      );
    }
    throw err;
  }
});
