/**
 * GET  /api/projects/[projectId]/submittals — list submittals in a project.
 * POST /api/projects/[projectId]/submittals — create a submittal register entry.
 *
 * Per SPEC_PHASE3_WEB.md §5 + §6 (S18 Submittals log).
 *
 * Per BR-DC2: submittal refs are auto-generated as "SUB-###" via the pure
 *           domain function nextSubmittalRef(existingRefs, deletedRefs).
 *           The high-water mark INCLUDES soft-deleted refs (BR-DC3 / GT-DC3 —
 *           refs are never reused). The route reads both lists with
 *           includeDeleted=true to honor this.
 *
 * Per BR-WEB-5: both routes verify the project exists AND is owned by the
 *           session user before doing anything.
 * Per BR-WEB-8: POST writes AuditLog.
 * Per BR-WEB-11: POST body validated with zod (SubmittalInputSchema, minus
 *           ref — that's auto-generated).
 */

import { Prisma } from "@prisma/client";
import {
  withErrorHandler,
  json,
  created,
  notFound,
  conflict,
  writeAuditLog,
} from "@/lib/api-helpers";
import { requireUserId } from "@/lib/auth";
import { getServices } from "@/lib/services";
import { verifyProjectOwnership } from "@/app/api/_lib/boq-helpers";
import { SubmittalInputSchema } from "@shared/schemas/doccontrol/entities";
import { nextSubmittalRef } from "@domain/doccontrol/numbering";

interface RouteContext {
  params: Promise<{ projectId: string }>;
}

// ─── GET list ─────────────────────────────────────────────────────────────

export const GET = withErrorHandler(async (_req: Request, ctx: RouteContext) => {
  const userId = await requireUserId();
  const { projectId } = await ctx.params;
  const services = getServices();

  const project = await verifyProjectOwnership(projectId, userId);
  if (!project) return notFound("Project not found");

  const submittals = await services.submittals.list(projectId);
  return json({ submittals });
});

// ─── POST create ──────────────────────────────────────────────────────────

export const POST = withErrorHandler(async (req: Request, ctx: RouteContext) => {
  const userId = await requireUserId();
  const { projectId } = await ctx.params;
  const services = getServices();

  const project = await verifyProjectOwnership(projectId, userId);
  if (!project) return notFound("Project not found");

  const body = await req.json();
  // Strip projectId + ref — the URL + numbering domain are the sources of truth.
  const {
    projectId: _ignoredProject,
    ref: _ignoredRef,
    ...rest
  } = body as Record<string, unknown>;
  // .omit({ ref: true }) — ref is auto-generated by the numbering domain.
  const SubmittalCreateBodySchema = SubmittalInputSchema.omit({ ref: true });
  const input = SubmittalCreateBodySchema.parse({ ...rest, projectId });

  // ─── Architecture proof: call the pure domain numbering function ───
  // The high-water mark INCLUDES soft-deleted refs (BR-DC3 — never reused).
  // We includeDeleted=true to fetch both live + soft-deleted refs in one pass.
  const liveSubmittals = await services.submittals.list(projectId, true);
  const existingRefs = liveSubmittals
    .filter((s) => s.deletedAt === null)
    .map((s) => s.ref);
  const deletedRefs = liveSubmittals
    .filter((s) => s.deletedAt !== null)
    .map((s) => s.ref);
  const ref = nextSubmittalRef(existingRefs, deletedRefs);

  try {
    const submittal = await services.submittals.create({
      projectId,
      ref,
      subjectEn: input.subjectEn,
      subjectAr: input.subjectAr ?? null,
      type: input.type,
      discipline: input.discipline,
      submittedDate: input.submittedDate ?? null,
      reviewPeriodDays: input.reviewPeriodDays,
      resubmissionNo: input.resubmissionNo,
      status: input.status,
    });

    await writeAuditLog({
      action: "submittal.create",
      entityType: "Submittal",
      entityId: submittal.id,
      afterJson: submittal,
    });

    return created(submittal);
  } catch (err) {
    // P2002 = unique constraint violation on (projectId, ref).
    // Shouldn't happen given nextSubmittalRef monotonicity, but defensive.
    if (err instanceof Prisma.PrismaClientKnownRequestError && err.code === "P2002") {
      return conflict(`Submittal ref "${ref}" already exists in this project`);
    }
    throw err;
  }
});
